# These are supported funding model platforms
github: [magicdude4eva] # Replace with up to 4 GitHub Sponsors-enabled usernames e.g., [user1, user2]
custom: ['https://www.paypal.com/paypalme/GerdNaschenweng'] 
