# Welcome to Jekyll!
#

# Site Settings
title: 'Curriculum Vitae / Resume of Gerd W. Naschenweng ~ CTO / Development Manager & Teamlead: e-Commerce, Java, DevOps, Linux. Located in Klagenfurt, Austria.'
url: 'https://www.naschenweng.info/cv'
domain: 'naschenweng.info'
baseurl: '/cv' #change it according to your repository name
description: 'Curriculum Vitae / Resume of Gerd W. Naschenweng ~ Java- & JEE specialist, Techlead and Development Manager / CTO. 20 years experience in e-Commerce, Java/JEE, Enterprise Architecture. Experienced Team Leader and CTO available for hire in Austria / Österreich / Kärnten / Klagenfurt, Germany / Deutschland'

# Style will be applied only after restarting the build or serve. Just choose one of the options.
theme_skin: ceramic # blue turquoise green berry orange ceramic
chrome_mobile_color: #use hex colors (ex:#1976d2) or leave empty if you don't want a color for chrome mobile searchbar

# Tracker
analytics: UA-55061128-1

# Plugins
plugins:
  - jekyll-last-modified-at

# Sass/SCSS
sass:
  sass_dir: _sass
  style: compressed # http://sass-lang.com/documentation/file.SASS_REFERENCE.html#output_style

# Build settings
compress-site: yes

encoding: "utf-8"

# Compression - http://jch.penibelst.de/
compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all
  ignore:
    envs: [development]
  blanklines: false
  profile: false
  startings: []

# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false


# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false


